# Generated by Django 4.2.1 on 2023-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_file', models.FileField(upload_to='uploads/<django.db.models.fields.CharField>/registration_data/')),
                ('results_file', models.FileField(upload_to='uploads/<django.db.models.fields.CharField>/results_data/')),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
